added new controller, that showes weather in NewYork
Nikolay961996/MadGeeks pull request #4
Opened 2023-04-25 15:52 UTC by ibrohimsub

2023-04-25 15:58 UTC, ibrohimsub commented
Я не понял как мне поставить Николая на Reviewers или это тебе автоматически попадает на проверку?

2023-04-29 17:15 UTC, Nikolay961996 requested changes
мелкая правка есть

2023-04-29 17:15 UTC, Nikolay961996 commented on Mad.Api/Mad.Api/Controllers/WeatherForecastController.cs
> +        [HttpOptions("options-current/weather-in-NewYork")]
```suggestion
        [HttpGet("options-current/weather-in-NewYork")]
```

2023-04-29 18:30 UTC, Nikolay961996 approved these changes

2023-04-29 19:54 UTC, closed without merging